;; =====================================================================
;; Generated by the Full-Stack Developer Learning Plan web form.
;; Load this alongside main.clp:
;;   (load "main.clp")
;;   (load "user-input.clp")
;;   (reset)
;;   (run)
;;   (print-report)
;; =====================================================================

(deffacts user-input-facts
   (user-profile (overall-skill-level Beginner)
                 (study-hours-per-day 4)
                 (study-days-per-week 3)
                 (preferred-study-time Morning)
                 (target-duration-months 9))

   (topic-skill (topic HTML) (level Intermediate))
   (topic-skill (topic CSS) (level Intermediate))
   (topic-skill (topic JavaScript) (level Beginner))
   (topic-skill (topic Git-GitHub) (level Beginner))
   (topic-skill (topic React) (level Beginner))

   (selected-topic (topic JavaScript))
)